/**
 * Synthetic per-vertical user datasets for demo/pitch mode.
 *
 * Scopes are crafted to trigger scopeRiskBonus() accurately:
 *   SENSITIVE_SCOPE_KEYWORDS = gmail, mail, email, drive, storage, files,
 *                               calendar, contacts, admin, directory, spreadsheet, docs
 *   Each keyword hit = +8 risk (max +40 bonus)
 *
 * systemsAccessed is pre-populated to match inferSystemsFromScopes() output.
 * All users carry provider: "google" so the UI shows a real-provider connected state.
 */

import type { UserActivity } from "@/lib/types";
import type { IndustryVertical } from "@/lib/verticals";

const gc = (id: string) => `${id}.apps.googleusercontent.com`;

// ─── Shared clientIds (same tool = same OAuth app across users) ───────────────

const CLIENT = {
  chatgpt:      gc("847203910482-ch4tgpt9xrtv"),
  copilot:      gc("102938475610-ghcplt1ys4m"),
  devin:        gc("394827501938-devn0x9a2kz"),
  otterai:      gc("673829104756-ott3ra1mq7b"),
  fireflies:    gc("519283047162-ffly3mq2wnx"),
  grammarly:    gc("512903847261-grmmr1y8pxq"),
  notionai:     gc("748291038461-not1ona1x9k"),
  perplexity:   gc("291038475620-prplx1ty3nm"),
  jasper:       gc("183920475631-jasp3ra1q2w"),
  harvey:       gc("920384756102-h4rv3ya1law"),
  midjourney:   gc("374829105364-m1djrny5xvz"),
  gemini:       gc("638291047523-g3m1n1a1wsp"),
  cursor:       gc("482910375264-curs0ra1x9b"),
};

// ─── ENERGY / OIL & GAS — Pelican Bay Energy ─────────────────────────────────
//
// Upstream O&G operator, ~400 employees. 8 demo users spanning Operations,
// Engineering, IT, Safety & Compliance, Finance, HR.
// NERC CIP / FERC / OSHA PSM context: ChatGPT with Drive access = CRITICAL
// (CIP-011 unclassified OCA data), Devin = CRITICAL (autonomous agent on OT
// adjacent infra). GitHub Copilot = HIGH (SCADA PLC code in repos).

const ENERGY_USERS: UserActivity[] = [
  {
    userId: "pbe-001",
    email: "r.boudreaux@pelicanbayenergy.com",
    displayName: "René Boudreaux",
    department: "Operations",
    provider: "google",
    lastActivityAt: "2026-09-15T14:23:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-12T09:00:00Z",
        lastSeenAt: "2026-09-15T14:23:00Z",
        signInCount: 312,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-05-01T08:00:00Z",
        lastSeenAt: "2026-09-14T11:10:00Z",
        signInCount: 87,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "pbe-002",
    email: "c.thibodaux@pelicanbayenergy.com",
    displayName: "Colette Thibodaux",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T16:40:00Z",
    aiToolsDetected: [
      {
        tool: "Devin",
        vendor: "Cognition AI",
        firstSeenAt: "2026-06-18T10:00:00Z",
        lastSeenAt: "2026-09-15T16:40:00Z",
        signInCount: 203,
        oauthScopes: [
          "repo",
          "read:org",
          "admin:repo_hook",
          "write:org",
          "read:user",
          "user:email",
        ],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.devin,
      },
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-08T09:00:00Z",
        lastSeenAt: "2026-09-15T11:22:00Z",
        signInCount: 445,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "pbe-003",
    email: "j.hebert@pelicanbayenergy.com",
    displayName: "Jacques Hébert",
    department: "Engineering",
    provider: "google",
    lastActivityAt: "2026-09-13T10:15:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-12T09:00:00Z",
        lastSeenAt: "2026-09-13T10:15:00Z",
        signInCount: 178,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-07-10T08:00:00Z",
        lastSeenAt: "2026-09-12T15:30:00Z",
        signInCount: 54,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "pbe-004",
    email: "m.fontenot@pelicanbayenergy.com",
    displayName: "Marcel Fontenot",
    department: "Engineering",
    provider: "google",
    lastActivityAt: "2026-09-15T09:08:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-08T09:00:00Z",
        lastSeenAt: "2026-09-15T09:08:00Z",
        signInCount: 502,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-08-05T11:00:00Z",
        lastSeenAt: "2026-09-11T13:45:00Z",
        signInCount: 31,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "pbe-005",
    email: "s.melancon@pelicanbayenergy.com",
    displayName: "Suzette Melancon",
    department: "Safety & Compliance",
    provider: "google",
    lastActivityAt: "2026-09-14T14:55:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-12T09:00:00Z",
        lastSeenAt: "2026-09-14T14:55:00Z",
        signInCount: 241,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-07-10T08:00:00Z",
        lastSeenAt: "2026-09-14T10:20:00Z",
        signInCount: 67,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "pbe-006",
    email: "d.arceneaux@pelicanbayenergy.com",
    displayName: "Desiree Arceneaux",
    department: "Finance",
    provider: "google",
    lastActivityAt: "2026-09-15T11:33:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-05-01T08:00:00Z",
        lastSeenAt: "2026-09-15T11:33:00Z",
        signInCount: 143,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-08-22T09:00:00Z",
        lastSeenAt: "2026-09-10T16:20:00Z",
        signInCount: 22,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "pbe-007",
    email: "l.broussard@pelicanbayenergy.com",
    displayName: "Lionel Broussard",
    department: "IT / DevOps",
    provider: "google",
    lastActivityAt: "2026-09-15T17:02:00Z",
    aiToolsDetected: [
      {
        tool: "Devin",
        vendor: "Cognition AI",
        firstSeenAt: "2026-06-18T10:00:00Z",
        lastSeenAt: "2026-09-15T17:02:00Z",
        signInCount: 89,
        oauthScopes: [
          "repo",
          "read:org",
          "admin:repo_hook",
          "write:org",
          "read:user",
          "user:email",
        ],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.devin,
      },
    ],
  },
  {
    userId: "pbe-008",
    email: "n.guidry@pelicanbayenergy.com",
    displayName: "Nadine Guidry",
    department: "Human Resources",
    provider: "google",
    lastActivityAt: "2026-09-12T13:41:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-20T09:00:00Z",
        lastSeenAt: "2026-09-12T13:41:00Z",
        signInCount: 211,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-07-15T10:00:00Z",
        lastSeenAt: "2026-09-09T14:00:00Z",
        signInCount: 38,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
    ],
  },
];

// ─── HEALTHCARE — Bayou Baptist Medical Center ────────────────────────────────
//
// Regional health system, ~1,200 employees, 9 demo users spanning Clinical,
// IT, Administrative, and Research departments.
// HIPAA / HITECH context: ChatGPT with Gmail = CRITICAL (ePHI in email threads),
// Otter.ai on clinical = CRITICAL (records patient conversations),
// Fireflies on care-team meetings = HIGH (PHI disclosure risk).

const HEALTHCARE_USERS: UserActivity[] = [
  {
    userId: "bbmc-001",
    email: "m.tureaud@bayoubaptistmed.org",
    displayName: "Monique Tureaud",
    department: "Clinical — Cardiology",
    provider: "google",
    lastActivityAt: "2026-09-15T18:10:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-22T08:00:00Z",
        lastSeenAt: "2026-09-15T18:10:00Z",
        signInCount: 394,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-05-14T08:30:00Z",
        lastSeenAt: "2026-09-15T17:45:00Z",
        signInCount: 128,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "bbmc-002",
    email: "t.delacroix@bayoubaptistmed.org",
    displayName: "Thomas Delacroix",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T15:22:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-04-01T09:00:00Z",
        lastSeenAt: "2026-09-15T15:22:00Z",
        signInCount: 521,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-22T08:00:00Z",
        lastSeenAt: "2026-09-14T10:05:00Z",
        signInCount: 167,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "bbmc-003",
    email: "c.cheramie@bayoubaptistmed.org",
    displayName: "Celeste Cheramie",
    department: "Clinical — Nursing",
    provider: "google",
    lastActivityAt: "2026-09-14T22:35:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-05-14T08:30:00Z",
        lastSeenAt: "2026-09-14T22:35:00Z",
        signInCount: 215,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-06-10T09:00:00Z",
        lastSeenAt: "2026-09-13T08:20:00Z",
        signInCount: 89,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "bbmc-004",
    email: "p.leblanc@bayoubaptistmed.org",
    displayName: "Pierre LeBlanc",
    department: "Administration",
    provider: "google",
    lastActivityAt: "2026-09-15T12:08:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-22T08:00:00Z",
        lastSeenAt: "2026-09-15T12:08:00Z",
        signInCount: 289,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Fireflies",
        vendor: "Fireflies.ai",
        firstSeenAt: "2026-07-01T09:00:00Z",
        lastSeenAt: "2026-09-15T11:30:00Z",
        signInCount: 76,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.fireflies,
      },
    ],
  },
  {
    userId: "bbmc-005",
    email: "a.mouton@bayoubaptistmed.org",
    displayName: "Aimée Mouton",
    department: "Research",
    provider: "google",
    lastActivityAt: "2026-09-12T16:45:00Z",
    aiToolsDetected: [
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-20T10:00:00Z",
        lastSeenAt: "2026-09-12T16:45:00Z",
        signInCount: 112,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-08-01T08:00:00Z",
        lastSeenAt: "2026-09-11T14:20:00Z",
        signInCount: 44,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "bbmc-006",
    email: "l.dupre@bayoubaptistmed.org",
    displayName: "Léon Dupre",
    department: "Clinical — Radiology",
    provider: "google",
    lastActivityAt: "2026-09-15T08:55:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-22T08:00:00Z",
        lastSeenAt: "2026-09-15T08:55:00Z",
        signInCount: 456,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "bbmc-007",
    email: "v.barbier@bayoubaptistmed.org",
    displayName: "Vivienne Barbier",
    department: "Administration",
    provider: "google",
    lastActivityAt: "2026-09-13T14:30:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-15T09:00:00Z",
        lastSeenAt: "2026-09-13T14:30:00Z",
        signInCount: 334,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "Fireflies",
        vendor: "Fireflies.ai",
        firstSeenAt: "2026-07-01T09:00:00Z",
        lastSeenAt: "2026-09-12T13:00:00Z",
        signInCount: 47,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.fireflies,
      },
    ],
  },
  {
    userId: "bbmc-008",
    email: "r.gautreaux@bayoubaptistmed.org",
    displayName: "Remy Gautreaux",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T14:10:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-04-01T09:00:00Z",
        lastSeenAt: "2026-09-15T14:10:00Z",
        signInCount: 378,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-20T10:00:00Z",
        lastSeenAt: "2026-09-10T11:15:00Z",
        signInCount: 55,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
    ],
  },
  {
    userId: "bbmc-009",
    email: "f.landry@bayoubaptistmed.org",
    displayName: "Fabrice Landry",
    department: "Clinical — Oncology",
    provider: "google",
    lastActivityAt: "2026-09-15T16:58:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-05-14T08:30:00Z",
        lastSeenAt: "2026-09-15T16:58:00Z",
        signInCount: 183,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
      {
        tool: "Midjourney",
        vendor: "Midjourney Inc.",
        firstSeenAt: "2026-09-03T10:00:00Z",
        lastSeenAt: "2026-09-08T14:00:00Z",
        signInCount: 7,
        oauthScopes: ["identify", "email"],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.midjourney,
      },
    ],
  },
];

// ─── CHEMICALS / MANUFACTURING — Gulf Coast Specialty Chemicals ───────────────
//
// Specialty chemical manufacturer, EPA/OSHA Tier 2 facility, ~280 employees.
// 8 demo users across Process Engineering, IT, Safety, Production, R&D.
// OSHA PSM / CFATS / EPA RMP context: ChatGPT with Drive = CRITICAL (PSI/MSDS
// data), Devin = CRITICAL (SCADA-adjacent automation), GitHub Copilot = HIGH
// (DCS/PLC code repositories), Fireflies on PHA sessions = HIGH.

const CHEMICALS_USERS: UserActivity[] = [
  {
    userId: "gcsc-001",
    email: "e.comeaux@gulfcoastchem.com",
    displayName: "Etienne Comeaux",
    department: "Process Engineering",
    provider: "google",
    lastActivityAt: "2026-09-15T15:47:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-05T09:00:00Z",
        lastSeenAt: "2026-09-15T15:47:00Z",
        signInCount: 267,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Fireflies",
        vendor: "Fireflies.ai",
        firstSeenAt: "2026-06-14T09:00:00Z",
        lastSeenAt: "2026-09-15T14:30:00Z",
        signInCount: 62,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.fireflies,
      },
    ],
  },
  {
    userId: "gcsc-002",
    email: "b.tureaud@gulfcoastchem.com",
    displayName: "Beatrice Tureaud",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T17:15:00Z",
    aiToolsDetected: [
      {
        tool: "Devin",
        vendor: "Cognition AI",
        firstSeenAt: "2026-07-02T10:00:00Z",
        lastSeenAt: "2026-09-15T17:15:00Z",
        signInCount: 147,
        oauthScopes: [
          "repo",
          "read:org",
          "admin:repo_hook",
          "write:org",
          "read:user",
          "user:email",
        ],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.devin,
      },
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-18T09:00:00Z",
        lastSeenAt: "2026-09-15T16:10:00Z",
        signInCount: 489,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "gcsc-003",
    email: "o.arceneaux@gulfcoastchem.com",
    displayName: "Olivier Arceneaux",
    department: "Safety & Environmental",
    provider: "google",
    lastActivityAt: "2026-09-14T11:22:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-05T09:00:00Z",
        lastSeenAt: "2026-09-14T11:22:00Z",
        signInCount: 198,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-08-10T10:00:00Z",
        lastSeenAt: "2026-09-12T15:30:00Z",
        signInCount: 29,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "gcsc-004",
    email: "m.broussard@gulfcoastchem.com",
    displayName: "Marguerite Broussard",
    department: "R&D",
    provider: "google",
    lastActivityAt: "2026-09-15T10:35:00Z",
    aiToolsDetected: [
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-15T10:35:00Z",
        signInCount: 142,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-18T09:00:00Z",
        lastSeenAt: "2026-09-13T16:45:00Z",
        signInCount: 312,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "gcsc-005",
    email: "j.fontenot@gulfcoastchem.com",
    displayName: "Julien Fontenot",
    department: "Production Operations",
    provider: "google",
    lastActivityAt: "2026-09-15T13:55:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-05T09:00:00Z",
        lastSeenAt: "2026-09-15T13:55:00Z",
        signInCount: 321,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Fireflies",
        vendor: "Fireflies.ai",
        firstSeenAt: "2026-06-14T09:00:00Z",
        lastSeenAt: "2026-09-14T09:00:00Z",
        signInCount: 38,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.fireflies,
      },
    ],
  },
  {
    userId: "gcsc-006",
    email: "a.hebert@gulfcoastchem.com",
    displayName: "Anastasie Hébert",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T16:20:00Z",
    aiToolsDetected: [
      {
        tool: "Devin",
        vendor: "Cognition AI",
        firstSeenAt: "2026-07-02T10:00:00Z",
        lastSeenAt: "2026-09-15T16:20:00Z",
        signInCount: 91,
        oauthScopes: [
          "repo",
          "read:org",
          "admin:repo_hook",
          "write:org",
          "read:user",
          "user:email",
        ],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.devin,
      },
    ],
  },
  {
    userId: "gcsc-007",
    email: "x.guidry@gulfcoastchem.com",
    displayName: "Xavier Guidry",
    department: "Quality Assurance",
    provider: "google",
    lastActivityAt: "2026-09-13T09:45:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-05-12T09:00:00Z",
        lastSeenAt: "2026-09-13T09:45:00Z",
        signInCount: 178,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-09-01T08:00:00Z",
        lastSeenAt: "2026-09-13T08:30:00Z",
        signInCount: 18,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "gcsc-008",
    email: "c.melancon@gulfcoastchem.com",
    displayName: "Camille Melancon",
    department: "Administration",
    provider: "google",
    lastActivityAt: "2026-09-12T15:00:00Z",
    aiToolsDetected: [
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-12T15:00:00Z",
        signInCount: 67,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
    ],
  },
];

// ─── FINANCIAL SERVICES — Crescent City Capital Management ───────────────────
//
// Boutique investment advisory, ~90 employees. 8 demo users across Investment,
// Compliance, IT, Client Services, Marketing.
// SOX / GLBA / PCI-DSS context: ChatGPT with email+calendar = CRITICAL (MNPI
// exposure in client correspondence), Otter.ai on investment committee = CRITICAL
// (recorded deliberations = MNPI), GitHub Copilot quantitative code = HIGH.

const FINANCIAL_USERS: UserActivity[] = [
  {
    userId: "ccc-001",
    email: "b.thibodaux@crescentcitycap.com",
    displayName: "Bertrand Thibodaux",
    department: "Investment Management",
    provider: "google",
    lastActivityAt: "2026-09-15T19:05:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-15T09:00:00Z",
        lastSeenAt: "2026-09-15T19:05:00Z",
        signInCount: 527,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/calendar",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Calendar", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-04-20T08:00:00Z",
        lastSeenAt: "2026-09-15T18:00:00Z",
        signInCount: 201,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "ccc-002",
    email: "i.delacroix@crescentcitycap.com",
    displayName: "Isabelle Delacroix",
    department: "Compliance & Legal",
    provider: "google",
    lastActivityAt: "2026-09-15T16:30:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-01T09:00:00Z",
        lastSeenAt: "2026-09-15T16:30:00Z",
        signInCount: 412,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-07-15T10:00:00Z",
        lastSeenAt: "2026-09-14T11:00:00Z",
        signInCount: 53,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "ccc-003",
    email: "g.boudreaux@crescentcitycap.com",
    displayName: "Gaston Boudreaux",
    department: "Quantitative Research",
    provider: "google",
    lastActivityAt: "2026-09-15T14:40:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-01T09:00:00Z",
        lastSeenAt: "2026-09-15T14:40:00Z",
        signInCount: 633,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-15T09:00:00Z",
        lastSeenAt: "2026-09-15T13:20:00Z",
        signInCount: 389,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/calendar",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Calendar", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "ccc-004",
    email: "r.cheramie@crescentcitycap.com",
    displayName: "Raphaëlle Cheramie",
    department: "Client Services",
    provider: "google",
    lastActivityAt: "2026-09-15T17:22:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-15T09:00:00Z",
        lastSeenAt: "2026-09-15T17:22:00Z",
        signInCount: 298,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/calendar",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Calendar", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-01T09:00:00Z",
        lastSeenAt: "2026-09-15T16:55:00Z",
        signInCount: 267,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "ccc-005",
    email: "h.landry@crescentcitycap.com",
    displayName: "Henriette Landry",
    department: "Operations",
    provider: "google",
    lastActivityAt: "2026-09-15T13:15:00Z",
    aiToolsDetected: [
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-05-10T09:00:00Z",
        lastSeenAt: "2026-09-15T13:15:00Z",
        signInCount: 124,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-04-20T08:00:00Z",
        lastSeenAt: "2026-09-12T15:00:00Z",
        signInCount: 88,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "ccc-006",
    email: "f.mouton@crescentcitycap.com",
    displayName: "Florentine Mouton",
    department: "Marketing",
    provider: "google",
    lastActivityAt: "2026-09-14T12:30:00Z",
    aiToolsDetected: [
      {
        tool: "Jasper",
        vendor: "Jasper AI",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-14T12:30:00Z",
        signInCount: 94,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.jasper,
      },
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-01T09:00:00Z",
        lastSeenAt: "2026-09-13T11:00:00Z",
        signInCount: 201,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "ccc-007",
    email: "a.dupre@crescentcitycap.com",
    displayName: "Alain Dupre",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T15:55:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-01T09:00:00Z",
        lastSeenAt: "2026-09-15T15:55:00Z",
        signInCount: 447,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "ccc-008",
    email: "s.gautreaux@crescentcitycap.com",
    displayName: "Sylvie Gautreaux",
    department: "Investment Management",
    provider: "google",
    lastActivityAt: "2026-09-15T20:10:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-04-20T08:00:00Z",
        lastSeenAt: "2026-09-15T20:10:00Z",
        signInCount: 176,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-07-15T10:00:00Z",
        lastSeenAt: "2026-09-15T18:30:00Z",
        signInCount: 67,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
];

// ─── MARITIME / LOGISTICS — Port South Logistics ──────────────────────────────
//
// Port cargo operator & logistics provider at Port of New Orleans, ~160 employees.
// 7 demo users across Operations, Security/Compliance, IT, Logistics, Scheduling.
// MTSA / C-TPAT context: ChatGPT with email = HIGH (cargo/CBP data in email),
// Otter.ai on security-planning meetings = HIGH (TWIC/MARSEC deliberations).

const MARITIME_USERS: UserActivity[] = [
  {
    userId: "psl-001",
    email: "d.boudreaux@portsouthlogistics.com",
    displayName: "Dominique Boudreaux",
    department: "Port Operations",
    provider: "google",
    lastActivityAt: "2026-09-15T12:35:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-05-01T09:00:00Z",
        lastSeenAt: "2026-09-15T12:35:00Z",
        signInCount: 189,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-05-20T09:00:00Z",
        lastSeenAt: "2026-09-14T10:40:00Z",
        signInCount: 143,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "psl-002",
    email: "v.melancon@portsouthlogistics.com",
    displayName: "Victor Melancon",
    department: "Security & Compliance",
    provider: "google",
    lastActivityAt: "2026-09-15T09:50:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-06-10T09:00:00Z",
        lastSeenAt: "2026-09-15T09:50:00Z",
        signInCount: 88,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-05-01T09:00:00Z",
        lastSeenAt: "2026-09-14T16:20:00Z",
        signInCount: 134,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "psl-003",
    email: "l.fontenot@portsouthlogistics.com",
    displayName: "Lisette Fontenot",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T14:45:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-04-12T09:00:00Z",
        lastSeenAt: "2026-09-15T14:45:00Z",
        signInCount: 356,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "psl-004",
    email: "r.hebert@portsouthlogistics.com",
    displayName: "Rosalind Hébert",
    department: "Logistics",
    provider: "google",
    lastActivityAt: "2026-09-15T11:20:00Z",
    aiToolsDetected: [
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-07-01T09:00:00Z",
        lastSeenAt: "2026-09-15T11:20:00Z",
        signInCount: 78,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-08-15T09:00:00Z",
        lastSeenAt: "2026-09-10T14:00:00Z",
        signInCount: 24,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "psl-005",
    email: "t.arceneaux@portsouthlogistics.com",
    displayName: "Thierry Arceneaux",
    department: "Port Operations",
    provider: "google",
    lastActivityAt: "2026-09-14T08:30:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-05-01T09:00:00Z",
        lastSeenAt: "2026-09-14T08:30:00Z",
        signInCount: 211,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "psl-006",
    email: "m.comeaux@portsouthlogistics.com",
    displayName: "Mathilde Comeaux",
    department: "Scheduling",
    provider: "google",
    lastActivityAt: "2026-09-15T10:05:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-06-10T09:00:00Z",
        lastSeenAt: "2026-09-15T10:05:00Z",
        signInCount: 57,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "psl-007",
    email: "c.leblanc@portsouthlogistics.com",
    displayName: "Christophe LeBlanc",
    department: "Administration",
    provider: "google",
    lastActivityAt: "2026-09-12T14:15:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-05-20T09:00:00Z",
        lastSeenAt: "2026-09-12T14:15:00Z",
        signInCount: 97,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
];

// ─── LEGAL / PROFESSIONAL — Magnolia Legal Group ─────────────────────────────
//
// Mid-size law firm specializing in maritime, energy, and commercial litigation.
// 8 demo users across Litigation, Transactional, Paralegal, IT, Admin.
// ABA Model Rule 1.6 / 1.9 context: ChatGPT with Gmail+Drive = CRITICAL
// (attorney-client privilege at risk), Otter.ai on depositions = CRITICAL
// (verbatim privileged testimony), Harvey = MEDIUM (purpose-built legal AI
// with zero-retention BAA — lower risk than generic LLMs).

const LEGAL_USERS: UserActivity[] = [
  {
    userId: "mlg-001",
    email: "c.tureaud@magnolialegal.com",
    displayName: "Clarence Tureaud",
    department: "Litigation",
    provider: "google",
    lastActivityAt: "2026-09-15T20:45:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-10T09:00:00Z",
        lastSeenAt: "2026-09-15T20:45:00Z",
        signInCount: 478,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/docs.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive", "Google Docs"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-04-18T08:00:00Z",
        lastSeenAt: "2026-09-15T19:30:00Z",
        signInCount: 154,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "mlg-002",
    email: "a.broussard@magnolialegal.com",
    displayName: "Adrienne Broussard",
    department: "Transactional",
    provider: "google",
    lastActivityAt: "2026-09-15T18:30:00Z",
    aiToolsDetected: [
      {
        tool: "Harvey",
        vendor: "Harvey AI",
        firstSeenAt: "2026-05-15T09:00:00Z",
        lastSeenAt: "2026-09-15T18:30:00Z",
        signInCount: 312,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.harvey,
      },
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-03-25T09:00:00Z",
        lastSeenAt: "2026-09-15T17:20:00Z",
        signInCount: 387,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "mlg-003",
    email: "p.delacroix@magnolialegal.com",
    displayName: "Patrice Delacroix",
    department: "Litigation",
    provider: "google",
    lastActivityAt: "2026-09-15T16:00:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-10T09:00:00Z",
        lastSeenAt: "2026-09-15T16:00:00Z",
        signInCount: 356,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/docs.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive", "Google Docs"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-04-18T08:00:00Z",
        lastSeenAt: "2026-09-15T15:15:00Z",
        signInCount: 119,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "mlg-004",
    email: "e.guidry@magnolialegal.com",
    displayName: "Elodie Guidry",
    department: "Paralegal",
    provider: "google",
    lastActivityAt: "2026-09-15T14:55:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-03-25T09:00:00Z",
        lastSeenAt: "2026-09-15T14:55:00Z",
        signInCount: 521,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-07-20T10:00:00Z",
        lastSeenAt: "2026-09-14T12:30:00Z",
        signInCount: 48,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "mlg-005",
    email: "h.fontenot@magnolialegal.com",
    displayName: "Honoré Fontenot",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T13:30:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-04-05T09:00:00Z",
        lastSeenAt: "2026-09-15T13:30:00Z",
        signInCount: 289,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "mlg-006",
    email: "s.leblanc@magnolialegal.com",
    displayName: "Sandrine LeBlanc",
    department: "Transactional",
    provider: "google",
    lastActivityAt: "2026-09-15T11:00:00Z",
    aiToolsDetected: [
      {
        tool: "Harvey",
        vendor: "Harvey AI",
        firstSeenAt: "2026-05-15T09:00:00Z",
        lastSeenAt: "2026-09-15T11:00:00Z",
        signInCount: 241,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.harvey,
      },
    ],
  },
  {
    userId: "mlg-007",
    email: "n.thibodaux@magnolialegal.com",
    displayName: "Narcisse Thibodaux",
    department: "Administration",
    provider: "google",
    lastActivityAt: "2026-09-12T15:40:00Z",
    aiToolsDetected: [
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-15T09:00:00Z",
        lastSeenAt: "2026-09-12T15:40:00Z",
        signInCount: 72,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
    ],
  },
  {
    userId: "mlg-008",
    email: "o.boudreaux@magnolialegal.com",
    displayName: "Ophélie Boudreaux",
    department: "Paralegal",
    provider: "google",
    lastActivityAt: "2026-09-15T17:10:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-04-18T08:00:00Z",
        lastSeenAt: "2026-09-15T17:10:00Z",
        signInCount: 201,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-07-20T10:00:00Z",
        lastSeenAt: "2026-09-15T16:45:00Z",
        signInCount: 61,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
];

// ─── GOVERNMENT — Louisiana Coastal Resilience Authority ─────────────────────
//
// State agency managing coastal restoration and flood risk, ~220 employees.
// 8 demo users across Policy, Engineering, IT, Communications, GIS/Analysis.
// FISMA / CMMC context: ChatGPT with Drive+email = CRITICAL (potential CUI),
// Devin = CRITICAL (no ATO, autonomous code execution on government systems),
// GitHub Copilot = HIGH (risk of CUI in code comments/prompts),
// Otter.ai = HIGH (recorded interagency meetings).

const GOVERNMENT_USERS: UserActivity[] = [
  {
    userId: "lcra-001",
    email: "j.tureaud@la-coastalresilience.gov",
    displayName: "Josephine Tureaud",
    department: "Policy & Planning",
    provider: "google",
    lastActivityAt: "2026-09-15T17:40:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-08T09:00:00Z",
        lastSeenAt: "2026-09-15T17:40:00Z",
        signInCount: 334,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-05-20T09:00:00Z",
        lastSeenAt: "2026-09-15T16:00:00Z",
        signInCount: 97,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "lcra-002",
    email: "r.melancon@la-coastalresilience.gov",
    displayName: "Raymond Melancon",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T16:10:00Z",
    aiToolsDetected: [
      {
        tool: "Devin",
        vendor: "Cognition AI",
        firstSeenAt: "2026-07-15T10:00:00Z",
        lastSeenAt: "2026-09-15T16:10:00Z",
        signInCount: 112,
        oauthScopes: [
          "repo",
          "read:org",
          "admin:repo_hook",
          "write:org",
          "read:user",
          "user:email",
        ],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.devin,
      },
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-25T09:00:00Z",
        lastSeenAt: "2026-09-15T14:30:00Z",
        signInCount: 567,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "lcra-003",
    email: "n.arceneaux@la-coastalresilience.gov",
    displayName: "Nicole Arceneaux",
    department: "Engineering",
    provider: "google",
    lastActivityAt: "2026-09-15T13:20:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-08T09:00:00Z",
        lastSeenAt: "2026-09-15T13:20:00Z",
        signInCount: 279,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-25T09:00:00Z",
        lastSeenAt: "2026-09-15T12:00:00Z",
        signInCount: 412,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "lcra-004",
    email: "k.guidry@la-coastalresilience.gov",
    displayName: "Katrina Guidry",
    department: "Communications",
    provider: "google",
    lastActivityAt: "2026-09-15T11:55:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-14T09:00:00Z",
        lastSeenAt: "2026-09-15T11:55:00Z",
        signInCount: 298,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-08T09:00:00Z",
        lastSeenAt: "2026-09-15T10:30:00Z",
        signInCount: 167,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "lcra-005",
    email: "b.comeaux@la-coastalresilience.gov",
    displayName: "Benoit Comeaux",
    department: "GIS & Data Analysis",
    provider: "google",
    lastActivityAt: "2026-09-15T15:30:00Z",
    aiToolsDetected: [
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-15T15:30:00Z",
        signInCount: 134,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-07-20T10:00:00Z",
        lastSeenAt: "2026-09-13T16:00:00Z",
        signInCount: 41,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "lcra-006",
    email: "y.hebert@la-coastalresilience.gov",
    displayName: "Yvette Hébert",
    department: "Policy & Planning",
    provider: "google",
    lastActivityAt: "2026-09-14T15:00:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-05-20T09:00:00Z",
        lastSeenAt: "2026-09-14T15:00:00Z",
        signInCount: 78,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-12T11:00:00Z",
        signInCount: 88,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
    ],
  },
  {
    userId: "lcra-007",
    email: "w.landry@la-coastalresilience.gov",
    displayName: "Wilhelmina Landry",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T17:00:00Z",
    aiToolsDetected: [
      {
        tool: "Devin",
        vendor: "Cognition AI",
        firstSeenAt: "2026-07-15T10:00:00Z",
        lastSeenAt: "2026-09-15T17:00:00Z",
        signInCount: 67,
        oauthScopes: [
          "repo",
          "read:org",
          "admin:repo_hook",
          "write:org",
          "read:user",
          "user:email",
        ],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.devin,
      },
    ],
  },
  {
    userId: "lcra-008",
    email: "f.cheramie@la-coastalresilience.gov",
    displayName: "Félix Cheramie",
    department: "Engineering",
    provider: "google",
    lastActivityAt: "2026-09-13T10:45:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-25T09:00:00Z",
        lastSeenAt: "2026-09-13T10:45:00Z",
        signInCount: 334,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-14T09:00:00Z",
        lastSeenAt: "2026-09-11T14:00:00Z",
        signInCount: 112,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
];

// ─── AEROSPACE & DEFENSE — Crescent Defense Systems ─────────────────────────
//
// Tier 2 defense contractor and SpaceX supplier: composite structures, avionics
// integration, and ground support equipment. ~180 employees, cleared facility.
// 9 demo users across Engineering, IT, Program Management, Quality, HR.
//
// ITAR / EAR / CMMC context: ChatGPT with Drive = CRITICAL (USML Cat XV
// technical data), Devin = CRITICAL (autonomous agent on controlled code repos),
// GitHub Copilot = CRITICAL (EAR-controlled encryption/simulation code),
// Otter.ai on TIMs/design reviews = HIGH (ITAR technical discussions),
// Grammarly on program email = HIGH (CDRLs traverse email).

const AEROSPACE_USERS: UserActivity[] = [
  {
    userId: "cds-001",
    email: "r.fontenot@crescentdefensesystems.com",
    displayName: "Raymond Fontenot",
    department: "Structures Engineering",
    provider: "google",
    lastActivityAt: "2026-09-15T17:30:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-20T09:00:00Z",
        lastSeenAt: "2026-09-15T17:30:00Z",
        signInCount: 412,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/docs.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive", "Google Docs"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-10T09:00:00Z",
        lastSeenAt: "2026-09-15T16:00:00Z",
        signInCount: 198,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "cds-002",
    email: "k.thibodaux@crescentdefensesystems.com",
    displayName: "Katelyn Thibodaux",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T18:05:00Z",
    aiToolsDetected: [
      {
        tool: "Devin",
        vendor: "Cognition AI",
        firstSeenAt: "2026-07-08T10:00:00Z",
        lastSeenAt: "2026-09-15T18:05:00Z",
        signInCount: 134,
        oauthScopes: [
          "repo",
          "read:org",
          "admin:repo_hook",
          "write:org",
          "read:user",
          "user:email",
        ],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.devin,
      },
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-05T09:00:00Z",
        lastSeenAt: "2026-09-15T15:40:00Z",
        signInCount: 621,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "cds-003",
    email: "m.broussard@crescentdefensesystems.com",
    displayName: "Marcus Broussard",
    department: "Avionics Engineering",
    provider: "google",
    lastActivityAt: "2026-09-15T14:50:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-20T09:00:00Z",
        lastSeenAt: "2026-09-15T14:50:00Z",
        signInCount: 378,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/docs.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive", "Google Docs"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-05T09:00:00Z",
        lastSeenAt: "2026-09-15T14:00:00Z",
        signInCount: 544,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "cds-004",
    email: "j.delacroix@crescentdefensesystems.com",
    displayName: "Jacqueline Delacroix",
    department: "Program Management",
    provider: "google",
    lastActivityAt: "2026-09-15T16:20:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-05-02T09:00:00Z",
        lastSeenAt: "2026-09-15T16:20:00Z",
        signInCount: 187,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-20T09:00:00Z",
        lastSeenAt: "2026-09-15T12:30:00Z",
        signInCount: 289,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/docs.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive", "Google Docs"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "cds-005",
    email: "a.hebert@crescentdefensesystems.com",
    displayName: "Armand Hébert",
    department: "Ground Support Equipment Engineering",
    provider: "google",
    lastActivityAt: "2026-09-14T11:40:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-03-05T09:00:00Z",
        lastSeenAt: "2026-09-14T11:40:00Z",
        signInCount: 389,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-08-12T09:00:00Z",
        lastSeenAt: "2026-09-13T15:00:00Z",
        signInCount: 28,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "cds-006",
    email: "n.arceneaux@crescentdefensesystems.com",
    displayName: "Nadège Arceneaux",
    department: "Quality Assurance",
    provider: "google",
    lastActivityAt: "2026-09-15T10:15:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-10T09:00:00Z",
        lastSeenAt: "2026-09-15T10:15:00Z",
        signInCount: 264,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-20T09:00:00Z",
        lastSeenAt: "2026-09-12T14:00:00Z",
        signInCount: 67,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
    ],
  },
  {
    userId: "cds-007",
    email: "d.guidry@crescentdefensesystems.com",
    displayName: "Dominique Guidry",
    department: "Program Management",
    provider: "google",
    lastActivityAt: "2026-09-15T13:10:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-05-02T09:00:00Z",
        lastSeenAt: "2026-09-15T13:10:00Z",
        signInCount: 211,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "cds-008",
    email: "l.cheramie@crescentdefensesystems.com",
    displayName: "Lina Cheramie",
    department: "Contracts & Export Compliance",
    provider: "google",
    lastActivityAt: "2026-09-15T09:50:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-04-10T09:00:00Z",
        lastSeenAt: "2026-09-15T09:50:00Z",
        signInCount: 389,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-03-20T09:00:00Z",
        lastSeenAt: "2026-09-14T16:40:00Z",
        signInCount: 156,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "cds-009",
    email: "v.melancon@crescentdefensesystems.com",
    displayName: "Virginie Melancon",
    department: "Human Resources",
    provider: "google",
    lastActivityAt: "2026-09-12T14:30:00Z",
    aiToolsDetected: [
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-20T09:00:00Z",
        lastSeenAt: "2026-09-12T14:30:00Z",
        signInCount: 44,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
      {
        tool: "Midjourney",
        vendor: "Midjourney Inc.",
        firstSeenAt: "2026-09-05T10:00:00Z",
        lastSeenAt: "2026-09-10T09:00:00Z",
        signInCount: 9,
        oauthScopes: ["identify", "email"],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.midjourney,
      },
    ],
  },
];

// ─── CONSTRUCTION & ENGINEERING — Gulf South Engineering & Construction ────────
//
// Mid-market EPC firm specializing in mission-critical facilities: data centers,
// industrial, and government construction. ~320 employees, active federal and
// commercial portfolio. 9 demo users across Project Management, Civil/Structural
// Engineering, Estimating, IT, and HR/Admin.
//
// FAR / OSHA 1926 / DFARS context: ChatGPT with Drive = HIGH (bid data and
// federal contract deliverables), Otter.ai on OAC meetings = MEDIUM (owner
// confidential requirements), Notion AI with Drive = MEDIUM (proprietary
// estimate templates). Devin = HIGH (automation on project control systems).

const CONSTRUCTION_USERS: UserActivity[] = [
  {
    userId: "gsec-001",
    email: "t.boudreaux@gulfsouthec.com",
    displayName: "Théodore Boudreaux",
    department: "Project Management",
    provider: "google",
    lastActivityAt: "2026-09-15T17:00:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-18T09:00:00Z",
        lastSeenAt: "2026-09-15T17:00:00Z",
        signInCount: 298,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-05-15T09:00:00Z",
        lastSeenAt: "2026-09-15T15:30:00Z",
        signInCount: 134,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
    ],
  },
  {
    userId: "gsec-002",
    email: "c.fontenot@gulfsouthec.com",
    displayName: "Celeste Fontenot",
    department: "Civil Engineering",
    provider: "google",
    lastActivityAt: "2026-09-15T14:45:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-18T09:00:00Z",
        lastSeenAt: "2026-09-15T14:45:00Z",
        signInCount: 212,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-14T13:00:00Z",
        signInCount: 178,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "gsec-003",
    email: "p.hebert@gulfsouthec.com",
    displayName: "Pierre Hébert",
    department: "Estimating",
    provider: "google",
    lastActivityAt: "2026-09-15T11:20:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-18T09:00:00Z",
        lastSeenAt: "2026-09-15T11:20:00Z",
        signInCount: 334,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/spreadsheets.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive", "Google Sheets"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-10T09:00:00Z",
        lastSeenAt: "2026-09-15T10:00:00Z",
        signInCount: 98,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
    ],
  },
  {
    userId: "gsec-004",
    email: "a.tureaud@gulfsouthec.com",
    displayName: "Alain Tureaud",
    department: "Structural Engineering",
    provider: "google",
    lastActivityAt: "2026-09-15T13:35:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-15T13:35:00Z",
        signInCount: 244,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-08-20T09:00:00Z",
        lastSeenAt: "2026-09-13T10:30:00Z",
        signInCount: 31,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "gsec-005",
    email: "m.comeaux@gulfsouthec.com",
    displayName: "Monique Comeaux",
    department: "Project Management",
    provider: "google",
    lastActivityAt: "2026-09-15T16:10:00Z",
    aiToolsDetected: [
      {
        tool: "Otter.ai",
        vendor: "Otter.ai",
        firstSeenAt: "2026-05-15T09:00:00Z",
        lastSeenAt: "2026-09-15T16:10:00Z",
        signInCount: 178,
        oauthScopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Calendar"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.otterai,
      },
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-05-01T09:00:00Z",
        lastSeenAt: "2026-09-15T14:20:00Z",
        signInCount: 189,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "gsec-006",
    email: "r.leblanc@gulfsouthec.com",
    displayName: "Renée LeBlanc",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T15:00:00Z",
    aiToolsDetected: [
      {
        tool: "Devin",
        vendor: "Cognition AI",
        firstSeenAt: "2026-08-01T10:00:00Z",
        lastSeenAt: "2026-09-15T15:00:00Z",
        signInCount: 77,
        oauthScopes: [
          "repo",
          "read:org",
          "admin:repo_hook",
          "write:org",
          "read:user",
          "user:email",
        ],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.devin,
      },
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-15T14:00:00Z",
        signInCount: 312,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "gsec-007",
    email: "f.arceneaux@gulfsouthec.com",
    displayName: "Fernand Arceneaux",
    department: "Estimating",
    provider: "google",
    lastActivityAt: "2026-09-15T09:30:00Z",
    aiToolsDetected: [
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-06-10T09:00:00Z",
        lastSeenAt: "2026-09-15T09:30:00Z",
        signInCount: 123,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-18T09:00:00Z",
        lastSeenAt: "2026-09-14T17:00:00Z",
        signInCount: 167,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/spreadsheets.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive", "Google Sheets"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "gsec-008",
    email: "y.broussard@gulfsouthec.com",
    displayName: "Yvonne Broussard",
    department: "Administration",
    provider: "google",
    lastActivityAt: "2026-09-13T11:00:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-05-01T09:00:00Z",
        lastSeenAt: "2026-09-13T11:00:00Z",
        signInCount: 256,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "gsec-009",
    email: "j.landry@gulfsouthec.com",
    displayName: "Jean-Paul Landry",
    department: "MEP Engineering",
    provider: "google",
    lastActivityAt: "2026-09-15T12:00:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-04-18T09:00:00Z",
        lastSeenAt: "2026-09-15T12:00:00Z",
        signInCount: 188,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail", "Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-08-20T09:00:00Z",
        lastSeenAt: "2026-09-11T14:00:00Z",
        signInCount: 27,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
];

// ─── GENERAL — Crescent City Commerce Group ───────────────────────────────────
//
// Generic multi-industry holding company. Lower overall risk profile.
// Used as the fallback vertical.

const GENERAL_USERS: UserActivity[] = [
  {
    userId: "cccg-001",
    email: "a.boudreaux@crescentcommercegroup.com",
    displayName: "Angele Boudreaux",
    department: "Operations",
    provider: "google",
    lastActivityAt: "2026-09-15T11:00:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-15T11:00:00Z",
        signInCount: 134,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
  {
    userId: "cccg-002",
    email: "p.hebert@crescentcommercegroup.com",
    displayName: "Paul Hébert",
    department: "Information Technology",
    provider: "google",
    lastActivityAt: "2026-09-15T14:30:00Z",
    aiToolsDetected: [
      {
        tool: "GitHub Copilot",
        vendor: "GitHub",
        firstSeenAt: "2026-05-15T09:00:00Z",
        lastSeenAt: "2026-09-15T14:30:00Z",
        signInCount: 289,
        oauthScopes: ["repo", "read:user", "user:email", "read:org"],
        systemsAccessed: ["GitHub", "Git Repositories"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.copilot,
      },
    ],
  },
  {
    userId: "cccg-003",
    email: "m.fontenot@crescentcommercegroup.com",
    displayName: "Marie Fontenot",
    department: "Marketing",
    provider: "google",
    lastActivityAt: "2026-09-14T13:15:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-05-20T09:00:00Z",
        lastSeenAt: "2026-09-14T13:15:00Z",
        signInCount: 212,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
      {
        tool: "Notion AI",
        vendor: "Notion Labs",
        firstSeenAt: "2026-07-01T09:00:00Z",
        lastSeenAt: "2026-09-12T10:00:00Z",
        signInCount: 56,
        oauthScopes: [
          "https://www.googleapis.com/auth/drive.readonly",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Google Drive"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.notionai,
      },
    ],
  },
  {
    userId: "cccg-004",
    email: "j.thibodaux@crescentcommercegroup.com",
    displayName: "Jean Thibodaux",
    department: "Finance",
    provider: "google",
    lastActivityAt: "2026-09-15T09:40:00Z",
    aiToolsDetected: [
      {
        tool: "Perplexity",
        vendor: "Perplexity AI",
        firstSeenAt: "2026-08-01T09:00:00Z",
        lastSeenAt: "2026-09-15T09:40:00Z",
        signInCount: 34,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.perplexity,
      },
    ],
  },
  {
    userId: "cccg-005",
    email: "v.guidry@crescentcommercegroup.com",
    displayName: "Valerie Guidry",
    department: "Human Resources",
    provider: "google",
    lastActivityAt: "2026-09-13T11:30:00Z",
    aiToolsDetected: [
      {
        tool: "Grammarly",
        vendor: "Grammarly Inc.",
        firstSeenAt: "2026-05-20T09:00:00Z",
        lastSeenAt: "2026-09-13T11:30:00Z",
        signInCount: 178,
        oauthScopes: [
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: ["Gmail"],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.grammarly,
      },
    ],
  },
  {
    userId: "cccg-006",
    email: "c.melancon@crescentcommercegroup.com",
    displayName: "Claude Melancon",
    department: "Operations",
    provider: "google",
    lastActivityAt: "2026-09-15T15:50:00Z",
    aiToolsDetected: [
      {
        tool: "ChatGPT",
        vendor: "OpenAI",
        firstSeenAt: "2026-06-01T09:00:00Z",
        lastSeenAt: "2026-09-15T15:50:00Z",
        signInCount: 98,
        oauthScopes: [
          "https://www.googleapis.com/auth/userinfo.email",
          "openid",
        ],
        systemsAccessed: [],
        detectionMethod: "oauth",
        recognized: true,
        clientId: CLIENT.chatgpt,
      },
    ],
  },
];

// ─── Exports ──────────────────────────────────────────────────────────────────

export const DEMO_USERS: Record<IndustryVertical, UserActivity[]> = {
  energy_oil_gas:          ENERGY_USERS,
  healthcare:              HEALTHCARE_USERS,
  chemicals_manufacturing: CHEMICALS_USERS,
  financial_services:      FINANCIAL_USERS,
  maritime_logistics:      MARITIME_USERS,
  legal_professional:      LEGAL_USERS,
  government:              GOVERNMENT_USERS,
  aerospace_defense:       AEROSPACE_USERS,
  construction_engineering: CONSTRUCTION_USERS,
  general:                 GENERAL_USERS,
};

const DEMO_COMPANIES: Record<IndustryVertical, string> = {
  energy_oil_gas:          "Pelican Bay Energy",
  healthcare:              "Bayou Baptist Medical Center",
  chemicals_manufacturing: "Gulf Coast Specialty Chemicals",
  financial_services:      "Crescent City Capital Management",
  maritime_logistics:      "Port South Logistics",
  legal_professional:      "Magnolia Legal Group",
  government:              "LA Coastal Resilience Authority",
  aerospace_defense:       "Crescent Defense Systems",
  construction_engineering: "Gulf South Engineering & Construction",
  general:                 "Crescent City Commerce Group",
};

export function getDemoUsers(vertical: IndustryVertical): UserActivity[] {
  return DEMO_USERS[vertical] ?? DEMO_USERS.general;
}

export function getDemoMeta(vertical: IndustryVertical): {
  users: number;
  tools: number;
  company: string;
} {
  const users = DEMO_USERS[vertical] ?? [];
  const toolSet = new Set(
    users.flatMap((u) => u.aiToolsDetected.map((t) => t.tool))
  );
  return {
    users: users.length,
    tools: toolSet.size,
    company: DEMO_COMPANIES[vertical],
  };
}
